name = 'Ahmedabad' 
two_char_name = 'Ah'
input_name=  'xpath://body/span[1]/span[1]/span[1]/input[1]'
name_click=  'xpath://body/span[1]/span[1]/span[2]/ul[1]/li[1]'
cal=  'xpath:/html[1]/body[1]/div[2]/div[1]/table[1]/tbody[1]/tr[5]/td[7]' 
cal_click=  'xpath://body[1]/div[2]/div[1]/table[1]/tbody[1]/tr[5]/td[5]'
checkin_date=  '08/01/2022'
checkout_date=  '04/05/2022'
dec_rooms=  'xpath=//div[@class="roomDec"]' 
adults=  'xpath://*[@id="hotels-search"]/div/div/div[3]/div/div/div/div/div[2]/div/div/div[1]'
nationality=  'xpath=//*[@id="nationality"]'
nation_select=  'xpath=//select[@id="nationality"]/option[text()="Iraq"]'
search=  'xpath=//button[@id="submit"]'
travellers= 'xpath://*[@id="hotels-search"]/div/div/div[3]/div/div/div/a'
inc_rooms= 'xpath=//*[@id="hotels-search"]/div/div/div[3]/div/div/div/div/div[1]/div/div/div[3]'
dec_adults = 'xpath=//*[@id="hotels-search"]/div/div/div[3]/div/div/div/div/div[2]/div/div/div[2]'
